// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  insert() — single call places number[idx] in sorted position
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: insert([1,2,8,5,4], 3) -> [1,2,5,8,4]", "[T1]")
{
    vector<int> v = {1, 2, 8, 5, 4};
    insert(v, 3);
    vector<int> exp = {1, 2, 5, 8, 4};
    REQUIRE(v == exp);
}

TEST_CASE("T1b: insert([2,4,6,8,3], 4) -> [2,3,4,6,8]", "[T1]")
{
    vector<int> v = {2, 4, 6, 8, 3};
    insert(v, 4);
    vector<int> exp = {2, 3, 4, 6, 8};
    REQUIRE(v == exp);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  insert() — already-sorted (no-op) and value-larger-than-prefix (stays)
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: insert on already-sorted prefix — value belongs at idx", "[T2]")
{
    vector<int> v = {1, 2, 3, 4, 5};
    vector<int> orig = v;
    insert(v, 4);  // 5 already in correct position
    REQUIRE(v == orig);
}

TEST_CASE("T2b: insert at idx=0 leaves array unchanged", "[T2]")
{
    vector<int> v = {7, 3, 9, 1};
    vector<int> orig = v;
    insert(v, 0);
    REQUIRE(v == orig);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  insertionsort() — full sort via repeated insert calls
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: insertionsort sorts [5,2,9,1,7,3,8] ascending", "[T3]")
{
    vector<int> v = {5, 2, 9, 1, 7, 3, 8};
    insertionsort(v);
    vector<int> exp = {1, 2, 3, 5, 7, 8, 9};
    REQUIRE(v == exp);
}

TEST_CASE("T3b: insertionsort sorts reverse-sorted vector", "[T3]")
{
    vector<int> v = {99, 80, 60, 40, 20, 10, 5, 1};
    insertionsort(v);
    vector<int> exp = {1, 5, 10, 20, 40, 60, 80, 99};
    REQUIRE(v == exp);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  Edge cases — single-element / all-equal / already-sorted
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: insertionsort on single-element vector leaves it unchanged", "[T4]")
{
    vector<int> v = {7};
    insertionsort(v);
    REQUIRE(v.size() == 1);
    REQUIRE(v[0] == 7);
}

TEST_CASE("T4b: insertionsort on already-sorted and all-equal vectors", "[T4]")
{
    vector<int> v1 = {1, 2, 3, 4, 5};
    vector<int> orig1 = v1;
    insertionsort(v1);
    REQUIRE(v1 == orig1);

    vector<int> v2 = {5, 5, 5, 5};
    vector<int> orig2 = v2;
    insertionsort(v2);
    REQUIRE(v2 == orig2);
}
